spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/share_note
    username: postgres
    password: 1234
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/share_note
    user: postgres
    password: 1234

jwt:
  secret: U29tZUJhc2U2NEVuY29kZWRSYW5kb21LZXlGb3JKV1Q=
  access-token:
    expiration: 30 # 30분(분단위)
  refresh-token:
    expiration: 1440 # 한달(분단위)